# Generated by Django 2.0.4 on 2018-04-08 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('degree_builder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='start_semester',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='user',
            name='start_year',
            field=models.IntegerField(default=2016),
        ),
    ]
