# Generated by Django 2.0.4 on 2018-04-09 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('degree_builder', '0002_auto_20180408_1115'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Users',
        ),
    ]
