# Generated by Django 2.0.4 on 2018-04-09 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('degree_builder', '0003_auto_20180409_0041'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='Student',
        ),
    ]
