# Generated by Django 2.0.4 on 2018-04-09 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('degree_builder', '0004_auto_20180409_0914'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='interests',
            field=models.CharField(default='[]', max_length=200),
        ),
    ]
