# Generated by Django 2.0.4 on 2018-04-09 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('degree_builder', '0005_student_interests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='degree',
            field=models.CharField(default='[]', max_length=1000),
        ),
    ]
