<<<<<<< HEAD
# Generated by Django 2.0.3 on 2018-08-16 08:22
=======
# Generated by Django 2.0.4 on 2018-08-18 13:00
>>>>>>> 2e0614b8b7da07c6df58c0d5b98136b8a06d5888

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('degree', '0003_auto_20180503_0840'),
    ]

    operations = [
        migrations.CreateModel(
            name='DegreePlanStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('plan', models.TextField()),
            ],
        ),
    ]
