# Generated by Django 2.2.5 on 2019-09-21 06:37

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('degree', '0022_auto_20181006_0913'),
    ]

    operations = [
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_id', models.CharField(default='', editable=False, max_length=10)),
                ('name', models.TextField(blank=True, default='')),
                ('code', models.CharField(blank=True, default='', max_length=9)),
                ('year', models.CharField(blank=True, default='', editable=False, max_length=4)),
                ('description', models.TextField(blank=True, default='')),
                ('graduation_stage', models.CharField(choices=[('undergraduate', 'undergraduate'), ('postgraduate', 'postgraduate')], default='undergraduate', max_length=60)),
                ('requirements', django.contrib.postgres.fields.jsonb.JSONField(default=list)),
                ('learning_outcomes', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='Minor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_id', models.CharField(default='', editable=False, max_length=10)),
                ('name', models.TextField(blank=True, default='')),
                ('code', models.CharField(blank=True, default='', max_length=9)),
                ('year', models.CharField(blank=True, default='', editable=False, max_length=4)),
                ('description', models.TextField(blank=True, default='')),
                ('graduation_stage', models.CharField(choices=[('undergraduate', 'undergraduate'), ('postgraduate', 'postgraduate')], default='undergraduate', max_length=60)),
                ('requirements', django.contrib.postgres.fields.jsonb.JSONField(default=list)),
                ('learning_outcomes', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='Specialisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_id', models.CharField(default='', editable=False, max_length=10)),
                ('name', models.TextField(blank=True, default='')),
                ('code', models.CharField(blank=True, default='', max_length=9)),
                ('year', models.CharField(blank=True, default='', editable=False, max_length=4)),
                ('description', models.TextField(blank=True, default='')),
                ('graduation_stage', models.CharField(choices=[('undergraduate', 'undergraduate'), ('postgraduate', 'postgraduate')], default='undergraduate', max_length=60)),
                ('requirements', django.contrib.postgres.fields.jsonb.JSONField(default=list)),
                ('learning_outcomes', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='studyoption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_year', models.CharField(default='', max_length=40)),
                ('option', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.AlterField(
            model_name='course',
            name='convenor',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='course',
            name='es_id',
            field=models.CharField(default=0, editable=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.CharField(blank=True, default=1000, max_length=4),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='course',
            name='year',
            field=models.CharField(blank=True, default=2018, max_length=4),
        ),
        migrations.AlterField(
            model_name='degreerequirement',
            name='code',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='degreerequirement',
            name='name',
            field=models.TextField(blank=True, default='', editable=False),
        ),
        migrations.AlterField(
            model_name='degreerequirement',
            name='required',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='degreerequirement',
            name='units',
            field=models.CharField(default='', max_length=10),
        ),
    ]
