# Generated by Django 2.2.5 on 2019-09-28 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('degree', '0023_auto_20190921_0637'),
    ]

    operations = [
        migrations.CreateModel(
            name='degree_requirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(default='', max_length=4)),
                ('code', models.CharField(default='', max_length=10)),
                ('name', models.TextField(blank=True, default='', editable=False)),
                ('units', models.CharField(default='', max_length=10)),
                ('required', models.TextField(blank=True, default='')),
            ],
        ),
    ]
