# Generated by Django 2.2.5 on 2019-10-06 02:36

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('degree', '0024_degree_requirement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_id', models.CharField(default=0, editable=False, max_length=10)),
                ('name', models.TextField(blank=True, default='')),
                ('code', models.CharField(blank=True, default='', max_length=9)),
                ('semesters', models.TextField(blank=True, default='')),
                ('prerequisite_text', models.TextField(blank=True, default='')),
                ('prerequisites', models.TextField(blank=True, default='')),
                ('incompatible', models.TextField(blank=True, default='')),
                ('min_units', models.CharField(blank=True, max_length=5)),
                ('level', models.CharField(blank=True, default=1000, max_length=4)),
                ('area', models.CharField(blank=True, default='', max_length=4)),
                ('description', models.TextField(blank=True, default='')),
                ('graduation_stage', models.CharField(choices=[('Undergraduate', 'Undergraduate'), ('Postgraduate', 'Postgraduate')], default='Undergraduate', max_length=60)),
                ('convenor', models.TextField(blank=True, default='')),
                ('units', models.CharField(blank=True, default='', max_length=60)),
                ('year', models.CharField(blank=True, default=2018, max_length=4)),
                ('minors', models.TextField(blank=True, default='')),
                ('majors', models.TextField(blank=True, default='')),
                ('learning_outcomes', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='DegreeRequirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(default='', max_length=4)),
                ('code', models.CharField(default='', max_length=10)),
                ('name', models.TextField(blank=True, default='', editable=False)),
                ('units', models.CharField(default='', max_length=10)),
                ('required', django.contrib.postgres.fields.jsonb.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_id', models.CharField(default='', editable=False, max_length=10)),
                ('name', models.TextField(blank=True, default='')),
                ('code', models.CharField(blank=True, default='', max_length=9)),
                ('year', models.CharField(blank=True, default='', editable=False, max_length=4)),
                ('description', models.TextField(blank=True, default='')),
                ('graduation_stage', models.CharField(choices=[('undergraduate', 'undergraduate'), ('postgraduate', 'postgraduate')], default='undergraduate', max_length=60)),
                ('requirements', django.contrib.postgres.fields.jsonb.JSONField(default=list)),
                ('learning_outcomes', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='Minor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_id', models.CharField(default='', editable=False, max_length=10)),
                ('name', models.TextField(blank=True, default='')),
                ('code', models.CharField(blank=True, default='', max_length=9)),
                ('year', models.CharField(blank=True, default='', editable=False, max_length=4)),
                ('description', models.TextField(blank=True, default='')),
                ('graduation_stage', models.CharField(choices=[('undergraduate', 'undergraduate'), ('postgraduate', 'postgraduate')], default='undergraduate', max_length=60)),
                ('requirements', django.contrib.postgres.fields.jsonb.JSONField(default=list)),
                ('learning_outcomes', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='Specialisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_id', models.CharField(default='', editable=False, max_length=10)),
                ('name', models.TextField(blank=True, default='')),
                ('code', models.CharField(blank=True, default='', max_length=9)),
                ('year', models.CharField(blank=True, default='', editable=False, max_length=4)),
                ('description', models.TextField(blank=True, default='')),
                ('graduation_stage', models.CharField(choices=[('undergraduate', 'undergraduate'), ('postgraduate', 'postgraduate')], default='undergraduate', max_length=60)),
                ('requirements', django.contrib.postgres.fields.jsonb.JSONField(default=list)),
                ('learning_outcomes', models.TextField(blank=True, default='')),
            ],
        ),
    ]
