# Generated by Django 2.2.5 on 2019-09-14 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('degree', '0043_specialisation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='es_id',
            field=models.CharField(default=0, editable=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.CharField(blank=True, default=1000, max_length=4),
        ),
        migrations.AlterField(
            model_name='course',
            name='year',
            field=models.CharField(blank=True, default=2018, max_length=4),
        ),
    ]
